name_model = "150M"
project = "debug_150m_zero_band"
type_model = "llama2"

[train]
micro_bs = 32 # change this base on the gpu
reshard_after_forward = true

[data]
num_workers = 1
dataset_name_or_paths = "datasets/fineweb-edu/data"

[optim]
batch_size = 512
warmup_steps = 500
total_steps = 8192


[optim.optim]
lr = 4e-4
