name_model = "150M"
project = "150m_zeroband_continuous"
type_model = "llama2"
metric_logger_type = "tensorboard,wandb"

[train]
micro_bs = 16 # change this base on the gpu

[data]
num_workers = 1
dataset_name_or_paths = "datasets/fineweb-edu/data"

[experiment]
fsdp = true
inner_scheduler_type = "continuous"
inner_scheduler_start = 10
inner_scheduler_end = 2000

[optim]
batch_size = 512
warmup_steps = 500
total_steps = 8192

[diloco]
inner_steps = 10

[optim.optim]
lr = 4e-4
