name_model = "150M"
project = "150m_zeroband_adaptive"
type_model = "llama2"
metric_logger_type = "tensorboard,wandb"
run_name = "vanilla-weighted"

[train]
micro_bs = 16 # change this base on the gpu

[data]
num_workers = 1
dataset_name_or_paths = "datasets/fineweb-edu/data"

[experiment]
fsdp = false
fused_optimizer = true
reverse = false

[optim]
batch_size = 512
warmup_steps = 500
total_steps = 1024

[diloco]
inner_steps = 100
compression = "no"

[optim.optim]
lr = 5e-5
